### ISSUE TITLE
Data in the Google drive is not available now. Could you please upload again and update the download url?

### ISSUE THREAD

**Issue by liuxiaoy16** [zbzhu99/NGSIM_Imitation#9]
Data in the Google drive is not available now. Could you please upload again and update the download url?
https://drive.google.com/file/d/1n0kvbS1psscTgYgQvTB6NZNTvZ4hSbzU/view?usp=sharing
https://drive.google.com/file/d/1oMzxTWK-wzpFufi2SryyD2Pa_l1tTEW0/view?usp=sharing

**Comment by zbzhu99** [comment]
The download link and installation guides have been updated in `README.md`, please check the latest commit 908d875.

**Comment by liuxiaoy16** [comment]
Thank you very much! I have already worked with pytorch-PPUU before and generate the sate action cost pairs in the format "car{idx}.pkl". But I noticed that the model required in your code is "all_data.pth". Do you have any idea how to get this? Thank you.
